import { useState } from 'react';
import { postReconciliation, type ReconciliationResult } from '../../services/api.js';

export interface VariancePayment { paymentId: string; clientId: string; amount: number; receiptReference?: string; status: string; }
export interface VarianceBatch { batchReference: string; branchId: string; collectionDate: string; expectedAmount: number; recordedAmount: number; submittedAmount: number; variance: number; status: string; decisionReason?: string | null; reviewedAt?: string | null; submittedBy: string; payments: VariancePayment[]; }
interface ManagerVarianceDashboardProps { batches: VarianceBatch[]; apiBaseUrl?: string; getToken: () => Promise<string>; onResolved: (batchReference: string, result: ReconciliationResult) => void; branchId?: string | null; }
export const hasDecisionReason = (reason: string): boolean => reason.trim().length > 0;

export function ManagerVarianceDashboard({ batches, apiBaseUrl = '', getToken, onResolved, branchId }: ManagerVarianceDashboardProps) {
  const [selected, setSelected] = useState<VarianceBatch | undefined>(); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [resolved, setResolved] = useState<Array<{ batchReference: string; status: string; reason: string }>>([]);
  const resolve = async (approve: boolean) => {
    if (!selected) return; if (!hasDecisionReason(reason)) { setError('A decision reason is required.'); return; } if (approve && !window.confirm('This action authorizes financial reconciliation and allocation. Continue?')) return;
    setBusy(true); setError(''); try { const token = await getToken(); const result = await postReconciliation({ branchId: selected.branchId, batchReference: selected.batchReference, expectedAmount: selected.expectedAmount, recordedAmount: selected.recordedAmount, submittedAmount: selected.submittedAmount, paymentIds: selected.payments.map((payment) => payment.paymentId), policyVersion: 'v1', managerOverride: approve, decision: approve ? 'approve' : 'reject', decisionReason: reason.trim() }, token, apiBaseUrl); setResolved((current) => [{ batchReference: selected.batchReference, status: result.status, reason: reason.trim() }, ...current.filter((item) => item.batchReference !== selected.batchReference)].slice(0, 5)); onResolved(selected.batchReference, result); setSelected(undefined); setReason(''); } catch (actionError) { setError(actionError instanceof Error ? actionError.message : 'RECONCILIATION_ACTION_FAILED'); } finally { setBusy(false); }
  };
  return <section className="field-card manager-dashboard" aria-labelledby="variance-title"><p className="eyebrow">Manager review</p><h2 id="variance-title">Reconciliation variances</h2>{branchId ? <p className="note">Review queue for authenticated branch {branchId}.</p> : <p className="note">No branch is assigned to this account.</p>}{error && <p className="form-error" role="alert">{error}</p>}{batches.length === 0 ? <p className="empty-state">No batches require review.</p> : <div className="variance-list">{batches.map((batch) => <button className="variance-row" type="button" key={batch.batchReference} onClick={() => setSelected(batch)}><span><strong>{batch.batchReference}</strong><small>{batch.collectionDate} · {batch.branchId}</small></span><span><strong>{batch.variance.toLocaleString()} UGX</strong><small>{batch.status}</small></span></button>)}</div>}{resolved.length > 0 && <div className="resolved-list"><p className="eyebrow">Recent decisions</p>{resolved.map((item) => <p key={item.batchReference}><strong>{item.batchReference}</strong> · {item.status} — {item.reason}</p>)}</div>}{selected && <div className="variance-detail" aria-live="polite"><div className="field-card-heading"><h3>{selected.batchReference}</h3><button className="text-button" type="button" onClick={() => setSelected(undefined)}>Close</button></div><div className="metric-grid"><div><span>Expected</span><strong>{selected.expectedAmount.toLocaleString()}</strong></div><div><span>Recorded</span><strong>{selected.recordedAmount.toLocaleString()}</strong></div><div><span>Submitted</span><strong>{selected.submittedAmount.toLocaleString()}</strong></div><div><span>Variance</span><strong>{selected.variance.toLocaleString()}</strong></div></div><ul className="payment-evidence">{selected.payments.map((payment) => <li key={payment.paymentId}><span>{payment.clientId} · {payment.amount.toLocaleString()} UGX</span><small>{payment.receiptReference ?? 'No server receipt'} · {payment.status}</small></li>)}</ul><label>Decision reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} required /></label><div className="action-row"><button className="secondary-button" type="button" disabled={busy} onClick={() => void resolve(false)}>Reject</button><button className="primary-button" type="button" disabled={busy} onClick={() => void resolve(true)}>Approve variance</button></div></div>}</section>;
}
